### ISSUE TITLE
Избавиться от exclude в preset-env

### ISSUE THREAD

**Issue by 7rulnik** [kupibilet-frontend/babel-preset-kupibilet#12]
Время исправлять ошибки прошлого: убейте плз https://github.com/kupibilet-frontend/babel-preset-kupibilet/blob/master/generateConfig.js#L46 и поставьте `usage`
https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental

`import "@babel/polyfill";` можно будет убрать из кода.

И неплохо было бы вкрутить https://babeljs.io/docs/en/babel-plugin-transform-runtime

**Comment by loonywizard** [comment]
Валентин, спасибо за ваше участие!

Провели эксперимент по изменению `useBuiltIns` на `usage`
В результате получили размер бандла kupibilet.ru (всех чанков) в gzipped на 7% больше, а также выросло время выполнения JavaScript
Данные результаты обусловлены тем, что при `usage` импорты, вставляемые в отдельные файлы, занимают больше места чем то место, которое мы экономим не добавляя некоторые полифилы

Безусловно, замеры скорости выполнения js всегда относительные, ведь на них существенно влияют другие процессы в ОС, но тем не менее, во всех экспериментах выполнение JS было медленнее на 10-20% с `usage`

<img width="490" alt="Screenshot 2019-08-05 at 16 32 26" src="https://user-images.githubusercontent.com/29688204/62468398-a572f100-b79e-11e9-94d7-4876125dc486.png">

**Comment by loonywizard** [comment]
> `import '@babel/polyfill';` можно будет убрать из кода

в связи с тем, что мы обновили `core-js` на 3-ю версию, это стало необходимостью, [подробнее тут](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill)

**Comment by 7rulnik** [comment]
Хм, прикольно. Не думал, что так может получиться. usage, конечно, надёжней, чем entry, но смотрите уже сами :)

Интересно откуда скорость выполнения растёт, по идее ведь не должно сильно вырастать, если уже такой же полифил был применён.

Так же, здесь более важной метрикой, как мне кажется, является размер initial чанков, а не всего бандла целиком.

Алсо, я пошёл бы по пути двух бандлов es5/es6

**Comment by loonywizard** [comment]
чем usage надёжнее entry? насколько я понимаю, преимущество usage в том, что он не вставляет ненужные полифилы, как от этого зависит надёжность?)

предположили, что скорость выполнения растёт оттого, что уходит время на резолвинг путей к полифилам

если под initial чанками имеются в виду чанки страниц (Главная, Поиск, Букинг), то у них собственный размер при usage также больше

два разных бандла - классная идея, мы когда-то думали об этом ноо так и не начали)

**Comment by 7rulnik** [comment]
При использовании entry с exclude может не полифилиться что-то, что должно.
По поводу резодвинга путей странно: там ведь резолв по moduleId происходит. Попробую у себя поиграться и посмотреть

Ну под initial я подразумеваю те модули, который загружаются на какой либо из страниц. За счёт entry у тебя раздувается условный vendor/main (ну, по идее).

**Comment by nezed** [comment]
Приветосы 🙃

- Никто и не говорит что мы собираемся использовать `entry` c `exclude`, как раз таки собираемся без него #18 
- Кажется что для нас важен суммарный вес всех JS файлов, загружаемых на конкретной странице. Выяснили что сокращение времени до интерактивности очень положительно сказывается на метриках конверсии
- При использовании usage, по идее, должен возрастать вес файлов до gzip, но в gzip не должен сильно увеличиваться, потому что все импорты полифилов должны выглядеть одинаково, но… моя логика тут не сработала
- Наша проблема почему `usage` хуже/медленнее [не нова](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#better-optimization-of-polyfill-loading), и вытекает в первую очередь из того, что мы собираем под таргет IE11. Из-за этого на каждый файл в учавствующий в сборке вставляются импорты на всё, какие только можно полифилы. Даже при том, что на клиенте собранные зависимости тянуться через moduleId - на каждый импорт происходит как минимум один вызов функции. А функции в JS по своей природе очень дорогие. Вот и получается, много импортов - много вызовов.
- Скорее всего, когда мы будем делать две сборки, где первая будет для IE11 с `entry`, а вторая для "свежачков" с `usage` - мы сможем получить существенный профит от него, а пока все-все полифилы для нас дешевле чем все-все импорты)
